server:
  port: 8080
  servlet:
    context-path: /crontab
spring:
  application:
    name: crontab
  datasource:
    url: jdbc:mysql:///crontab?useUnicode=true&characterEncoding=utf-8
    username: root
    password: fanhui66
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#logging:
#  level:
#    # 打印sql
#    cn.itfh.crontab.dao: debug





mybatis:
  mapper-locations: classpath:mapper/*.xml
